
sudo: false
language: java
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"

install:
  - echo "$HOME/.m2/settings.xml"
  - /bin/cat $HOME/.m2/settings.xml
  - mvn -B --show-version dependency:resolve

script: mvn -B verify

deploy:
  -
    provider: script
    script: "mvn -s settings.xml -DskipTests deploy"
    skip_cleanup: true
    on:
        tags: true
